spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gdg_web?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: "tiger1234!"
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  sql:
    init:
      mode: always  # data-skill.sql 항상 실행
      data-locations: classpath:data-skill.sql

jwt:
  secret: VGhpcyBpcyBhIHZlcnkgc2ChOoJlIHNlY3JldCBrZXkgZm9yIEpXVCAoMzJiYnl0ZXMpIQ==  # 예시 비밀 키 (Base64 인코딩된 문자열)
  accessExpiration: 3600000                 # 1시간 (3600000 밀리초)
  refreshExpiration: 604800000                     # 7일 (604800000 밀리초)

file:
  upload:
    path: ${FILE_UPLOAD_PATH:/home/ubuntu/uploads}
    url-prefix: /files

google:
  oauth2:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri-local: http://localhost:5173/api/auth/callback/google
    redirect-uri-prod: https://gdgoc-web-fe.vercel.app/api/auth/callback/google
    token-uri: https://oauth2.googleapis.com/token

